(add-hook 'term-mode-hook
          (lambda ()
            (define-key term-raw-map (kbd "C-c z") 'my-prefix)
            (when window-system
              (set-face-foreground 'term-color-black   "#000000")
              (set-face-foreground 'term-color-red     "#CC0000")
              (set-face-foreground 'term-color-green   "#4E9A06")
              (set-face-foreground 'term-color-yellow  "#C4A000")
              (set-face-foreground 'term-color-blue    "#3465A4")
              (set-face-foreground 'term-color-magenta "#75507B")
              (set-face-foreground 'term-color-cyan    "#06989A")
              (set-face-foreground 'term-color-white   "#D3D7CF")
              (set-face-background 'term-color-black   "#000000")
              (set-face-background 'term-color-red     "#CC0000")
              (set-face-background 'term-color-green   "#4E9A06")
              (set-face-background 'term-color-yellow  "#C4A000")
              (set-face-background 'term-color-blue    "#3465A4")
              (set-face-background 'term-color-magenta "#75507B")
              (set-face-background 'term-color-cyan    "#06989A")
              (set-face-background 'term-color-white   "#D3D7CF")
              )
            ))
