(require 'xt-mouse)
(add-hook 'after-make-frame-functions
          (lambda (f)
            (select-frame f)
            (if (not (window-system))
                (progn
                  (if (not xterm-mouse-mode)
                      (xterm-mouse-mode))
                  (if (or (string-match "^screen" (getenv "TERM"))
                          (string-match "^xterm" (getenv "TERM"))
                          (string-match "^rxvt" (getenv "TERM"))
                          )
                      (let ((m function-key-map))
                        (let ((function-key-map local-function-key-map))
                          (require 'xterm-extras)
                          (xterm-extra-keys)
                          (setq local-function-key-map function-key-map)
                          )
                        (setq function-key-map m)))
                  ))))
